### ISSUE TITLE
includes fail

### ISSUE THREAD

**Issue by Spica2** [Wscats/compile-hero#4]
e.g. include style.css fails

**Comment by Wscats** [comment]
@Spica2  Because I haven't tried this situation, I will give you a reply and suggestions after I test.

**Comment by Wscats** [comment]
@Spica2  I tried it and found it works, you can try the code.
```scss
/* Define mixin with two arguments */
@mixin bordered($color, $width) {
  border: $width solid $color;
}

.myArticle {
  @include bordered(blue, 1px); // Call mixin with two values
}

.myNotes {
  @include bordered(red, 2px); // Call mixin with two values
}
```
