### ISSUE TITLE
CSS does not compile correctly from SCSS

### ISSUE THREAD

**Issue by drift2000** [Wscats/compile-hero#46]
When I write  in SCSS like this

```css
.category-item {
    border: 1px solid #d0d0d0;
    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);

    :hover {
        border: 1px solid #797979;
    }
}
```

in CSS I will have this

```css
.category-item {
    border: 1px solid #d0d0d0;
    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
}
.category-item :hover {
    border: 1px solid #797979;
}
```

but it's not what I want to see. I won't see 

```css
.category-item {
    border: 1px solid #d0d0d0;
    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
}
.category-item:hover {
    border: 1px solid #797979;
}
```

**Comment by Wscats** [comment]
> When I write in SCSS like this
> 
> ```css
> .category-item {
>     border: 1px solid #d0d0d0;
>     box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
> 
>     :hover {
>         border: 1px solid #797979;
>     }
> }
> ```
> 
> in CSS I will have this
> 
> ```css
> .category-item {
>     border: 1px solid #d0d0d0;
>     box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
> }
> .category-item :hover {
>     border: 1px solid #797979;
> }
> ```
> 
> but it's not what I want to see. I won't see
> 
> ```css
> .category-item {
>     border: 1px solid #d0d0d0;
>     box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);
> }
> .category-item:hover {
>     border: 1px solid #797979;
> }
> ```

Using the `&` with the child combinator. https://css-tricks.com/the-sass-ampersand

```scss
.category-item {
    border: 1px solid #d0d0d0;
    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.3);

    &:hover {
        border: 1px solid #797979;
    }
}
```

If you think the plugin can help you solve the problem, please give us a five-star praise. https://marketplace.visualstudio.com/items?itemName=Wscats.eno&ssr=false#review-details
